# Generated by Django 4.2 on 2023-05-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, default='cover-default--book.svg', null=True, upload_to=''),
        ),
    ]
