# Generated by Django 4.2.1 on 2023-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
